[package]
name = "heracles-master"
version = "0.4.0"
authors = ["Heracles Authors <heracles@cpssd.net>"]

[dependencies]
cerberus-proto = { path = "../proto" }
chrono = "0.4"
clap = "~2.26"
failure = "0.1.1"
fern = "0.5.3"
grpc = "0.2.1"
log = "0.4"
